apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  JWT_SECRET: {{ .Values.config.jwtSecret | quote }}
  USER_SERVICE_ADDR: {{ .Values.config.userServiceAddr | quote }}
  PRODUCT_SERVICE_ADDR: {{ .Values.config.productServiceAddr | quote }}
  INVENTORY_SERVICE_ADDR: {{ .Values.config.inventoryServiceAddr | quote }}