# Dev environment overrides
# Only specify values that DIFFER from values.yaml

namespace: ecommerce-dev

replicaCount: 1

image:
  tag: 8eb8a93

  
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"