# Dev environment overrides
# Only specify values that DIFFER from values.yaml

replicaCount: 1

image:
  tag: 712d158

postgres:
  password: postgres
  
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"