apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  GRPC_PORT: {{ .Values.config.grpcPort | quote }}
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  REDIS_ADDR: {{ .Values.config.redisAddr | quote }}
  REDIS_PASSWORD: {{ .Values.config.redisPassword | quote }}
  LOCK_TTL_SECONDS: {{ .Values.config.lockTTLSeconds | quote }}