apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.grpcPort }}
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090