prometheus:
  enabled: true
  image: prom/prometheus:v3.0.0
  port: 9090
  scrapeInterval: 15s
  targets:
    - name: user-service
      address: user-service:8001
    - name: product-service
      address: product-service:8002
    - name: order-service
      address: order-service:8004
    - name: inventory-service
      address: inventory-service:9090

grafana:
  enabled: true
  image: grafana/grafana:11.3.0
  port: 3000
  adminUser: admin
  adminPassword: admin   # dev only