replicaCount: 3

image:
  tag: latest

config:
  jwtSecret: "CHANGE_ME_IN_PRODUCTION"
  mongoURI: "CHANGE_ME_IN_PRODUCTION"

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"