apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: databases
  namespace: argocd
spec:
  project: ecommerce

  destination:
    namespace: ecommerce-dev
    server: https://kubernetes.default.svc

  source:
    repoURL: https://github.com/bishtpramod19/ecommerce-platform.git
    targetRevision: main
    path: infra/helm/databases
    helm:
      valueFiles:
        - values-dev.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true